#
# Creating a Service and corresponding Deployment in the Namespace project-k 
# to launch a Nginx Web Server with 1 Replicas.
#
# The Service named svc-nginx-simple is listening at port 8080 
# with a Type of NodePort.
#
# The Deployment 
apiVersion: v1
kind: Service
metadata:
  namespace: project-k
  name: svc-nginx-namespace-project-k-lb
  labels:
    run: svc-nginx-namespace-project-k
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project-k
  name: deployment-nginx-namespace-project-k-lb
  labels:
    app: nginx
    namespace: project-k
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      namespace: project-k
      env: dev
  template:
    metadata:
      namespace: project-k
      labels:
        app: nginx
        namespace: project-k
        env: dev
    spec:
      containers:
      - name: container-nginx-namespace-project-k-lb
        image: nginx:1.14.2
        ports:
        - containerPort: 80