apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: project-k
  name: project-k
spec:
  finalizers:  # here the dead 'kubernetes' finalizers used for preventing the Namespace being deleted accidentally.
  - kubernetes